
server:
  port: 5050

spring:
  application:
    name: Being Abroad
  user: being
  password: being
  datasource:
    url: jdbc:h2:mem:beingdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
#    hibernate:
#      ddl-auto: true
#      generate-ddl: true

